Modified logic to fetch poolednormal Library Samples.
mskcc/LimsRest pull request #177
Opened 2020-09-17 23:12 UTC by ajay-p-sharma

2020-09-18 11:39 UTC, l-wagner approved these changes

2020-09-18 12:13 UTC, DavidStreid requested changes

2020-09-18 12:13 UTC, DavidStreid commented on src/main/java/org/mskcc/limsrest/service/sequencingqc/UpdateLimsSampleLevelSequencingQcTask.java
> +        if (idVals.size() == 2) {
could you comment why this is the case? 

Like, do the 2 ID values need to be POOLEDNORMAL_IDENTIFIER & CONTROL_IDENTIFIER?

2020-09-21 21:04 UTC, DavidStreid approved these changes

2020-09-21 21:04 UTC, DavidStreid commented on src/main/java/org/mskcc/limsrest/service/sequencingqc/UpdateLimsSampleLevelSequencingQcTask.java
> +                // Older SampleId values started with "CTRL" for POOLEDNORMAL control Samples. With last update, the control Samples now
this is why we do `idVals.size() == 2` on line 244?

2020-09-25 20:19 UTC, merged